import { Metadata } from 'next'
import { NavLinks } from './ui/nav-links'

export const metadata: Metadata = {
    title: 'Main Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <NavLinks />
        <main>{children}</main>
      </body>
    </html>
  )
}
